version: "3"

volumes:
  _postgres_data:

services:
  db:
    container_name: quiz_db
    image: postgres:13
    networks:
      - backend
    volumes:
      - _postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"
  migrations:
    container_name: quiz_migrations
    build: .
    networks:
      - backend
    profiles:
      - migrate
    volumes:
      - ./:/code/
    command: alembic upgrade head
    depends_on:
      - db
  web:
    container_name: quiz_web
    build: .
    networks:
      - backend
    env_file: 
     - .env
    depends_on:
     - db
    volumes:
      - ./:/code
    expose:
      - "8000"
    command: python -m uvicorn main:app --reload --host 0.0.0.0
    labels:
      - traefik.port=80
      - traefik.http.routers.fastapi.rule=Host(`localhost`)
  traefik:
    container_name: quiz_traefik
    image: traefik:v2.2
    networks:
      - backend
    ports:
      - "8080:8080"
      - "80:80"
    volumes:
      - "./traefik.dev.toml:/etc/traefik/traefik.toml"
      - "/var/run/docker.sock:/var/run/docker.sock"

networks:
  backend:
    driver: bridge
