version: "3"

volumes:
   _postgres_data:

services:
  db:
    container_name: quiz_db
    image: postgres:13
    volumes:
      - _postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"
  web:
    container_name: quiz_web
    build: .
    env_file: 
     - .env
    depends_on:
     - db
    ports:
      - "80:8000"
    volumes:
      - ./:/code
    command: uvicorn main:app --reload --host 0.0.0.0
    