version: "3"

volumes:
  _postgres_data:

networks:
  backend:
    driver: bridge

services:
  db:
    container_name: db
    image: postgres:13
    networks:
      - backend
    volumes:
      - _postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5433:5432"
  migrations:
    container_name: migrations
    build: .
    networks:
      - backend
    profiles:
      - migrate
    volumes:
      - ./:/code/
    command: alembic upgrade head
    depends_on:
      - db
      - web
  web:
    build: .
    deploy:
      replicas: 3
    networks:
      - backend
    env_file:
     - .env
    depends_on:
     - db
    volumes:
      - ./:/code
    expose:
      - "8000"
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000
  nginx:
    container_name: nginx
    image: nginx
    networks:
      - backend
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
      - db
